/* =========================================================
   WC DEV — BASE DE PROBLEMAS (diagnóstico por sintoma)
   Cada item: o que a pessoa VÊ acontecer → causas → correções.
   Campos: id, lang, tema, titulo, sintomas[], causas[], correcoes[],
           errado/certo (exemplo), compat (versão), confianca, origem,
           regras (regras do analisador que acham esse problema no código)
   Pra adicionar: copie um bloco. Sintomas = frases como o aluno fala.
   ========================================================= */

window.WCDEV = window.WCDEV || { temas: [] };
WCDEV.problemas = WCDEV.problemas || [];

WCDEV.problemas.push(
  /* ======================= PAWN / SA-MP ======================= */
  { id: "p-unknown-command", lang: "pawn", tema: "comandos", titulo: "\"SERVER: Unknown command\" mesmo com o comando funcionando",
    sintomas: ["unknown command", "server unknown command", "aparece unknown command", "comando funciona mas aparece unknown", "comando da unknown command", "comando nao existe"],
    causas: ["O comando não termina com {{return 1;}} (no zcmd, retorno 0 = \"comando desconhecido\").", "Deu um erro de execução no meio do comando (array index out of bounds, por exemplo) e ele parou antes do return.", "O nome no {{CMD:}} está diferente do que o jogador digitou.", "Sem {{#include <zcmd>}}, o {{CMD:}} vira uma função comum e o comando nunca é chamado."],
    correcoes: ["Termine todo comando com {{return 1;}}.", "Instale o plugin **crashdetect**: ele mostra no {{server_log.txt}} a linha exata do erro de execução.", "Confira se o {{#include <zcmd>}} está no topo."],
    errado: "CMD:vida(playerid, params[])\n{\n    SetPlayerHealth(playerid, 100.0);\n}", certo: "CMD:vida(playerid, params[])\n{\n    SetPlayerHealth(playerid, 100.0);\n    return 1;\n}",
    compat: "zcmd / Pawn.CMD, SA-MP 0.3.7 e open.mp", confianca: "alta", origem: "comportamento documentado do zcmd", regras: ["comando-sem-return", "dependencia-ausente"] },
  { id: "p-local-zerada", lang: "pawn", tema: "variáveis", titulo: "Variável nova (local) vem com lixo? Preciso zerar?",
    sintomas: ["variavel local vem com lixo", "preciso zerar a variavel", "new vem com lixo", "variavel comeca com valor aleatorio", "precisa inicializar variavel", "valor estranho na variavel nova", "strcat com lixo"],
    causas: ["**Não vem lixo:** em Pawn todo {{new}} começa com **0** (números) ou texto vazio, tanto local quanto global. Eu conferi rodando o código: mesmo depois de outra função usar a memória, {{new lista[128];}} começa vazio.", "O que realmente \"vem com valor de outro\" são **arrays globais por jogador** ({{Dinheiro[MAX_PLAYERS]}}): eles não zeram sozinhos quando outro jogador entra no mesmo id.", "E {{static}} dentro de função **guarda** o valor entre uma chamada e outra (de propósito)."],
    correcoes: ["Local: não precisa zerar (pode deixar {{new total;}}).", "Global por jogador: zere no {{OnPlayerConnect}}.", "Se você usa {{-1}} como \"vazio\", preencha com {{-1}} no começo: {{new Carro[MAX_PLAYERS] = { -1, ... };}} (o padrão é 0, não -1)."],
    certo: "stock Somar(const v[], n)\n{\n    new total;   // começa em 0\n    for (new i = 0; i < n; i++) total += v[i];\n    return total;\n}", compat: "Pawn 3.x (SA-MP e open.mp)", confianca: "alta", origem: "semântica do Pawn, conferida executando no runtime AMX", regras: ["valor-padrao", "dados-herdados"] },
  { id: "p-dados-nao-salvam", lang: "pawn", tema: "salvamento", titulo: "Jogador perde dinheiro, nível ou itens quando sai",
    sintomas: ["perde o dinheiro quando sai", "perde tudo quando sai", "nao salva", "dados nao salvam", "perdeu o nivel", "quando loga de novo volta pro zero", "conta zerada", "nao salvou a conta", "perde o level", "perde o xp", "servidor reiniciou e perdeu tudo"],
    causas: ["A função de salvar não é chamada no {{OnPlayerDisconnect}}.", "O campo novo (ex: XP, itens) foi criado no enum mas **não foi colocado** na função de salvar/carregar.", "Salva antes de carregar: se o jogador sai antes de logar, grava a conta **zerada** por cima.", "O servidor caiu: só salva ao sair, nunca durante o jogo.", "Esqueceu o {{DOF2_SaveFile()}} / {{DOF2_Exit()}} no {{OnGameModeExit}}."],
    correcoes: ["Chame {{SalvarConta(playerid)}} no {{OnPlayerDisconnect}}, **só se estiver logado** ({{if (Jogador[playerid][jLogado])}}).", "Todo campo novo do enum: adicione no salvar **e** no carregar.", "Salve também num timer (ex: a cada 10 minutos) pra não perder tudo se o servidor cair.", "No {{OnGameModeExit}}: salve todos e chame {{DOF2_Exit();}}."],
    compat: "DOF2 e MySQL", confianca: "alta", origem: "padrão comum de gamemodes RP", regras: ["dados-salvos"] },
  { id: "p-herda-dados", lang: "pawn", tema: "dados do jogador", titulo: "Jogador novo entra com dinheiro, admin ou itens de outro",
    sintomas: ["entrou com dinheiro de outro", "jogador novo entrou com", "entra com dinheiro de outro", "jogador novo entrou admin", "herdou os dados", "entra com o level de outro", "dados de outro jogador", "veio com itens de outro"],
    causas: ["O array {{Jogador[playerid]}} **não é zerado** no {{OnPlayerConnect}}: o novo jogador recebe o mesmo id de quem saiu e herda os dados."],
    correcoes: ["No {{OnPlayerConnect}}: {{new vazio[E_JOGADOR]; Jogador[playerid] = vazio;}} (antes de carregar a conta)."],
    certo: "public OnPlayerConnect(playerid)\n{\n    new vazio[E_JOGADOR];\n    Jogador[playerid] = vazio;\n    return 1;\n}", compat: "SA-MP e open.mp", confianca: "alta", origem: "ids do SA-MP são reaproveitados", regras: [] },
  { id: "p-crash-array", lang: "pawn", tema: "crash", titulo: "Comando para no meio / \"array index out of bounds\"",
    sintomas: ["array index out of bounds", "index out of bounds", "comando para no meio", "comando nao termina", "run time error 4", "crashdetect array", "servidor da erro quando uso o comando com id errado"],
    causas: ["Usou um id inválido como posição de array, geralmente o {{INVALID_PLAYER_ID}} (65535) que o sscanf devolve quando o jogador digitado não existe.", "Loop com {{<=}} no limite ({{i <= MAX_PLAYERS}}).", "{{killerid}} usado sem conferir no {{OnPlayerDeath}} (vem 65535 quando ninguém matou).", "{{listitem}} maior que o array de opções."],
    correcoes: ["Depois do sscanf: {{if (!IsPlayerConnected(alvo)) return ...;}}", "Loops: {{i < MAX_PLAYERS}} (menor, não menor-igual).", "{{if (killerid != INVALID_PLAYER_ID)}} antes de usar o killerid."],
    compat: "SA-MP 0.3.7, open.mp (com crashdetect o erro aparece no log)", confianca: "alta", origem: "erro 4 da máquina AMX", regras: ["sscanf-id-sem-validar", "loop-passa-do-limite", "killerid-invalido", "playerid-sem-validar"] },
  { id: "p-dinheiro-hack", lang: "pawn", tema: "dinheiro", titulo: "Dinheiro aparecendo do nada / jogador com dinheiro infinito",
    sintomas: ["dinheiro infinito", "dinheiro do nada", "money hack", "jogador com muito dinheiro", "dinheiro aparecendo", "duplicando dinheiro", "bug de dinheiro", "pagar com valor negativo"],
    causas: ["Comando de pagar/transferir aceita **valor negativo** (pagar -5000 = roubar).", "Não confere se o jogador **tem** o dinheiro antes de transferir.", "O servidor confia no {{GetPlayerMoney}}, que o cliente (hack) consegue alterar.", "Comando de admin de dar dinheiro sem checar permissão."],
    correcoes: ["{{if (valor < 1 || valor > GetPlayerMoney(playerid)) return ...;}}", "Guarde o dinheiro no seu enum ({{Jogador[playerid][jDinheiro]}}) e só confie nele; sincronize com {{ResetPlayerMoney}} + {{GivePlayerMoney}}.", "Comando de dar dinheiro: confira o nível de admin antes."],
    compat: "SA-MP e open.mp", confianca: "alta", origem: "brechas comuns em servidores RP", regras: ["quantidade-negativa", "comando-sem-permissao"] },
  { id: "p-msg-nao-chega-kick", lang: "pawn", tema: "kick", titulo: "Mensagem antes do Kick/Ban não aparece pro jogador",
    sintomas: ["mensagem do kick nao aparece", "jogador nao ve o motivo do kick", "kick sem mensagem", "ban nao mostra mensagem", "mensagem antes do kick nao chega"],
    causas: ["{{Kick}}/{{Ban}} desconecta **na hora**, antes da mensagem chegar no jogador."],
    correcoes: ["Mande a mensagem e dê o kick com um timer de ~500 ms: {{SetTimerEx(\"KickAtrasado\", 500, false, \"i\", playerid);}}"],
    certo: "forward KickAtrasado(playerid);\npublic KickAtrasado(playerid) { Kick(playerid); }\n\n// no comando:\nSendClientMessage(alvo, -1, \"Você foi kickado.\");\nSetTimerEx(\"KickAtrasado\", 500, false, \"i\", alvo);",
    compat: "SA-MP 0.3x e open.mp", confianca: "alta", origem: "comportamento do SA-MP desde 0.3x", regras: [] },
  { id: "p-msg-nao-aparece", lang: "pawn", tema: "mensagens", titulo: "Mensagem não aparece no chat (ou aparece cortada)",
    sintomas: ["mensagem nao aparece", "sendclientmessage nao aparece", "mensagem cortada", "texto cortado no chat", "mensagem some", "format corta o texto"],
    causas: ["Texto com mais de **144** caracteres (o chat corta ou nem mostra).", "O array do {{format}} é pequeno pro texto.", "A cor tem o último par {{00}} (transparente), tipo {{0xFF000000}}.", "A mensagem foi enviada pra um id errado (ex: {{playerid}} no lugar do {{alvo}})."],
    correcoes: ["Divida mensagens grandes em duas.", "Use {{new msg[144];}} e {{format(msg, sizeof(msg), ...)}}.", "Cores terminam com {{FF}}: {{0xFF0000FF}}."],
    compat: "SA-MP e open.mp", confianca: "alta", origem: "limite do chat do SA-MP", regras: ["mensagem-144", "format-tamanho"] },
  { id: "p-acento", lang: "pawn", tema: "mensagens", titulo: "Acentos aparecem errados no chat (Ã§, Ã£...)",
    sintomas: ["acento errado", "acentos bugados", "aparece simbolo estranho no lugar do acento", "ç aparece errado", "caracteres estranhos no chat"],
    causas: ["O arquivo .pwn está salvo em **UTF-8**, mas o SA-MP usa a codificação Windows-1252."],
    correcoes: ["Salve o .pwn como **ANSI / Windows-1252** (no Notepad++: Codificação → Converter para ANSI).", "Ou escreva sem acento nas mensagens do jogo."],
    compat: "SA-MP 0.3.7 (open.mp tem opções de codificação)", confianca: "média", origem: "codificação do cliente SA-MP", regras: [] },
  { id: "p-timer-nao-roda", lang: "pawn", tema: "timers", titulo: "Timer não roda (a função nunca é chamada)",
    sintomas: ["timer nao funciona", "timer nao roda", "settimer nao chama", "funcao do timer nunca roda", "timer nao executa", "payday nao cai"],
    causas: ["A função do timer não é {{public}} (stock ou função comum não é achada).", "Falta o {{forward}} da função.", "O nome no {{SetTimer(\"Nome\", ...)}} está diferente do nome da função.", "O SetTimer está num lugar que nunca roda (ex: dentro de um if que nunca é verdadeiro)."],
    correcoes: ["{{forward Nome();}} e {{public Nome()}}.", "Confira o nome **igualzinho**, com maiúsculas.", "Coloque um {{print(\"timer rodou\");}} dentro da função pra ver no console."],
    certo: "forward Payday();\npublic Payday()\n{\n    print(\"payday rodou\");\n    return 1;\n}\n\npublic OnGameModeInit()\n{\n    SetTimer(\"Payday\", 60000, true);\n    return 1;\n}",
    compat: "SA-MP e open.mp", confianca: "alta", origem: "SetTimer só chama public", regras: ["timer-sem-public"] },
  { id: "p-timer-duplicado", lang: "pawn", tema: "timers", titulo: "Timer roda várias vezes / coisa acontecendo em dobro",
    sintomas: ["timer roda duas vezes", "payday caindo duas vezes", "acontece em dobro", "mensagem repetindo", "timer duplicado", "servidor ficando lento com o tempo"],
    causas: ["{{SetTimer}} repetindo dentro do {{OnPlayerConnect}} ou {{OnPlayerSpawn}}: cada vez que alguém entra/nasce, cria **mais um** timer.", "Timer por jogador que nunca é cancelado com {{KillTimer}} quando ele sai."],
    correcoes: ["Timers globais: crie **só no** {{OnGameModeInit}}.", "Timer por jogador: guarde o id ({{TimerJogador[playerid] = SetTimerEx(...)}}) e dê {{KillTimer}} no {{OnPlayerDisconnect}}."],
    compat: "SA-MP e open.mp", confianca: "alta", origem: "padrão comum de bug", regras: [] },
  { id: "p-servidor-trava", lang: "pawn", tema: "desempenho", titulo: "Servidor trava / para de responder / lag",
    sintomas: ["servidor travou", "servidor trava", "servidor congelou", "server travando", "lag no servidor", "servidor parou de responder", "servidor fica lento"],
    causas: ["Um {{while}} que nunca termina (nada muda a condição).", "Loop pesado num timer muito rápido (ex: percorrer todos os jogadores a cada 100 ms).", "{{OnPlayerUpdate}} com código pesado (ele roda várias vezes por segundo pra cada jogador).", "Leitura/escrita de arquivo ou banco dentro de loop."],
    correcoes: ["Confira todo {{while}}: algo dentro dele precisa mudar a condição.", "Timers de 1 segundo ou mais pra coisas comuns.", "Deixe o {{OnPlayerUpdate}} o mais leve possível.", "Use o plugin **crashdetect** e um {{printf}} pra achar onde trava."],
    compat: "SA-MP e open.mp", confianca: "média", origem: "o Pawn roda numa thread só", regras: ["while-infinito"] },
  { id: "p-dialog-errado", lang: "pawn", tema: "dialogs", titulo: "Dialog responde errado / clicar em um dialog faz ação de outro",
    sintomas: ["dialog errado", "dialog bugado", "clico no dialog e acontece outra coisa", "dialog responde errado", "dialog nao funciona", "botao do dialog nao faz nada"],
    causas: ["O {{OnDialogResponse}} não confere o {{dialogid}}.", "Dois dialogs com o **mesmo id**.", "Esqueceu o {{return 1;}} depois de tratar um dialog (cai no tratamento de outro).", "Não confere o {{response}} (o jogador clicou em Cancelar)."],
    correcoes: ["Use {{#define}} com ids diferentes pra cada dialog.", "{{if (dialogid == DIALOG_X) { if (!response) return 1; ... return 1; }}}", "{{return 0;}} no fim do callback."],
    compat: "SA-MP e open.mp", confianca: "alta", origem: "OnDialogResponse é um callback só pra todos", regras: ["dialog-sem-id"] },
  { id: "p-textdraw-nao-aparece", lang: "pawn", tema: "textdraw", titulo: "TextDraw não aparece na tela",
    sintomas: ["textdraw nao aparece", "td nao aparece", "hud nao aparece", "playertextdraw nao mostra", "texto na tela nao aparece"],
    causas: ["Criou mas não mostrou ({{TextDrawShowForPlayer}} / {{PlayerTextDrawShow}}).", "Posição fora da tela (a tela vai de 0 a 640 x 0 a 448).", "Mudou cor/tamanho depois de mostrar e não mostrou de novo.", "Cor com transparência total ({{...00}} no fim).", "Passou do limite (2048 globais / 256 por jogador)."],
    correcoes: ["Depois de configurar, chame o Show.", "Teste numa posição segura, tipo {{(320.0, 200.0)}}.", "Depois de mudar algo, mostre de novo."],
    compat: "SA-MP 0.3.7 e open.mp", confianca: "alta", origem: "documentação de TextDraws", regras: [] },
  { id: "p-comando-todo-mundo", lang: "pawn", tema: "permissões", titulo: "Qualquer jogador consegue usar comando de admin",
    sintomas: ["qualquer um consegue usar", "qualquer um usa meu comando", "qualquer jogador usa", "qualquer um consegue usar meu comando", "qualquer um usa o comando de admin", "jogador usou comando de admin", "todo mundo consegue kickar", "comando de admin sem permissao", "jogador comum usando /ban"],
    causas: ["O comando não confere o nível de admin **antes** de agir.", "Confere depois de já ter feito a ação.", "Confere com {{=}} em vez de {{>=}} ou {{==}}."],
    correcoes: ["Primeira linha do comando: {{if (Jogador[playerid][jAdmin] < 1) return SendClientMessage(playerid, -1, \"Sem permissão.\");}}"],
    compat: "SA-MP e open.mp", confianca: "alta", origem: "brecha comum", regras: ["comando-sem-permissao"] },
  { id: "p-checkpoint", lang: "pawn", tema: "checkpoints", titulo: "Checkpoint paga errado ou some",
    sintomas: ["checkpoint nao funciona", "checkpoint some", "checkpoint paga errado", "checkpoint de outro emprego", "entrei no checkpoint e nada aconteceu"],
    causas: ["O SA-MP só tem **um checkpoint por jogador**: criar outro apaga o anterior.", "O {{OnPlayerEnterCheckpoint}} não sabe qual sistema criou o checkpoint."],
    correcoes: ["Guarde qual sistema criou o checkpoint (ex: {{Jogador[playerid][jTrabalhando] = true;}}) e confira no callback.", "Para muitos checkpoints, use o plugin **streamer** (checkpoints dinâmicos)."],
    compat: "SA-MP e open.mp", confianca: "alta", origem: "limite do SA-MP", regras: [] },
  { id: "p-sscanf", lang: "pawn", tema: "comandos", titulo: "Comando aceita qualquer coisa / parâmetros vêm zerados",
    sintomas: ["comando aceita qualquer coisa", "parametro vem zero", "sscanf nao funciona", "comando sem parametro funciona errado", "id vem errado", "valor sempre zero"],
    causas: ["O retorno do {{sscanf}} não é conferido (ele devolve diferente de 0 quando o jogador digitou errado).", "O formato não bate com as variáveis (ex: {{\"ui\"}} com uma variável só).", "Plugin sscanf não está carregado no {{server.cfg}}."],
    correcoes: ["{{if (sscanf(params, \"ui\", id, valor)) return SendClientMessage(playerid, -1, \"Use: /cmd [id] [valor]\");}}", "Uma letra por variável.", "Confira a linha {{plugins sscanf}} no server.cfg."],
    compat: "sscanf 2.x", confianca: "alta", origem: "documentação do sscanf", regras: ["sscanf-id-sem-validar"] },
  { id: "p-xp-nivel", lang: "pawn", tema: "progressão", titulo: "XP some ou o jogador sobe de nível errado",
    sintomas: ["xp some", "perde xp quando sobe", "sobe so um nivel", "level nao sobe", "ganhei muito xp e subi so um level", "xp ficou negativo", "nivel sobe facil demais", "nao upa"],
    causas: ["Usa {{if}} em vez de {{while}}: com muito XP de uma vez, sobe só um nível.", "Usa {{while}} mas não recalcula o XP necessário: sobe vários níveis pelo preço do primeiro.", "Zera o XP ({{= 0}}) em vez de descontar ({{-= precisa}}): perde o que sobrou.", "Função de dar XP aceita valor negativo.", "Nível e XP não são salvos."],
    correcoes: ["{{while (XP >= precisa) { XP -= precisa; nivel++; precisa = (nivel + 1) * 100; }}}", "Recuse XP negativo: {{if (xp <= 0) return 0;}}", "Salve nível e XP junto da conta."],
    compat: "qualquer gamemode", confianca: "alta", origem: "análise de sistemas de XP", regras: ["if-que-devia-ser-while", "xp-sem-recalculo", "xp-excedente-perdido", "quantidade-negativa"] },
  { id: "p-include", lang: "pawn", tema: "compilação", titulo: "\"cannot read from file\" / include não encontrado",
    sintomas: ["cannot read from file", "fatal error 100", "include nao encontrado", "nao acha o include", "error 100"],
    causas: ["O arquivo {{.inc}} não está na pasta {{pawno/include}} (ou {{qawno/include}}).", "Nome escrito diferente ({{sscanf}} vs {{sscanf2}})."],
    correcoes: ["Baixe o include e coloque na pasta include do compilador que você usa.", "Confira o nome exato do arquivo."],
    compat: "Pawno / Qawno", confianca: "alta", origem: "mensagem do compilador", regras: [] },
  { id: "p-plugin", lang: "pawn", tema: "plugins", titulo: "Plugin não carrega (\"Failed\" no console)",
    sintomas: ["plugin nao carrega", "failed to load plugin", "plugin failed", "sscanf nao carrega", "plugin nao funciona", "native function not registered"],
    causas: ["Falta o nome do plugin na linha {{plugins}} do {{server.cfg}} (open.mp: {{config.json}}).", "No Linux, o nome precisa terminar com {{.so}}; no Windows, o arquivo é {{.dll}}.", "Plugin de 64 bits num servidor de 32 bits.", "Faltam bibliotecas (Visual C++ Redistributable no Windows)."],
    correcoes: ["Windows: {{plugins sscanf.dll}}. Linux: {{plugins sscanf.so}}.", "Baixe a versão do plugin pro seu sistema e versão do servidor."],
    compat: "SA-MP 0.3.7 / open.mp", confianca: "média", origem: "erros comuns de instalação", regras: [] },
  { id: "p-senha-vazia", lang: "pawn", tema: "login", titulo: "Login aceita senha vazia / qualquer senha",
    sintomas: ["login aceita qualquer senha", "senha vazia entra", "entra sem senha", "login bugado", "qualquer senha funciona"],
    causas: ["{{strcmp}} com texto **vazio** devolve 0 (= \"igual\"), então senha vazia passa.", "Compara com {{if (strcmp(...))}} sem o {{!}} (lógica invertida).", "Guarda senha em texto puro (perigoso se o arquivo vazar)."],
    correcoes: ["Antes de comparar: {{if (isnull(inputtext)) return MostrarLogin(playerid);}}", "Guarde a senha com hash ({{SHA256_PassHash}} com salt, ou o plugin bcrypt)."],
    compat: "SA-MP 0.3.7 R2+ (SHA256_PassHash)", confianca: "alta", origem: "comportamento do strcmp", regras: [] },

  /* ======================= PYTHON ======================= */
  { id: "py-input-soma", lang: "python", tema: "tipos", titulo: "Soma dá errado ou TypeError com input",
    sintomas: ["soma junta os numeros", "2 + 2 da 22", "input nao soma", "typeerror can only concatenate", "unsupported operand type str", "soma de input errada"],
    causas: ["O {{input()}} sempre devolve **texto**. \"2\" + \"2\" junta e vira \"22\"."],
    correcoes: ["Converta: {{n = int(input(\"Número: \"))}} (ou {{float}} pra decimal)."],
    errado: "a = input(\"A: \")\nb = input(\"B: \")\nprint(a + b)", certo: "a = int(input(\"A: \"))\nb = int(input(\"B: \"))\nprint(a + b)",
    compat: "Python 3", confianca: "alta", origem: "documentação do Python", regras: [] },
  { id: "py-indent", lang: "python", tema: "sintaxe", titulo: "IndentationError / código fora do bloco",
    sintomas: ["indentationerror", "expected an indented block", "unexpected indent", "erro de indentacao", "codigo fora do if"],
    causas: ["Depois de uma linha que termina com {{:}} a próxima precisa de recuo.", "Misturou TAB com espaço."],
    correcoes: ["Use sempre **4 espaços** por nível.", "No editor, configure TAB pra inserir espaços."],
    compat: "Python 3", confianca: "alta", origem: "mensagem do Python", regras: [] },
  { id: "py-arquivo", lang: "python", tema: "arquivos", titulo: "FileNotFoundError ao abrir arquivo",
    sintomas: ["filenotfounderror", "no such file or directory", "nao acha o arquivo", "arquivo nao encontrado python"],
    causas: ["O caminho é relativo à **pasta de onde você rodou** o programa, não à pasta do .py.", "Nome ou extensão diferente (ex: {{dados.txt.txt}})."],
    correcoes: ["Use o caminho a partir do arquivo: {{from pathlib import Path; caminho = Path(__file__).parent / \"dados.txt\"}}"],
    compat: "Python 3.4+", confianca: "alta", origem: "documentação do Python", regras: [] },
  { id: "py-index", lang: "python", tema: "listas", titulo: "IndexError: list index out of range",
    sintomas: ["list index out of range", "indexerror", "indice fora da lista"],
    causas: ["Pediu uma posição que não existe: a lista vai de 0 até {{len(lista) - 1}}.", "Loop com {{range(len(lista) + 1)}}."],
    correcoes: ["Percorra com {{for item in lista:}}.", "Antes de acessar: {{if i < len(lista):}}"],
    compat: "Python 3", confianca: "alta", origem: "mensagem do Python", regras: [] },

  /* ======================= HTML / CSS ======================= */
  { id: "css-nao-aplica", lang: "css", tema: "css", titulo: "CSS não faz efeito nenhum",
    sintomas: ["css nao funciona", "css nao pega", "estilo nao aplica", "mudei o css e nada mudou", "css nao carrega"],
    causas: ["O {{<link>}} aponta pro caminho errado.", "Cache do navegador (mostra o CSS antigo).", "Outra regra mais específica está ganhando.", "Erro de digitação (falta {{;}} ou {{}}}) invalida o resto."],
    correcoes: ["F12 → aba Network: veja se o .css carregou (status 200).", "Ctrl+F5 pra recarregar sem cache.", "F12 → Elements → Styles: a regra riscada é a que perdeu."],
    compat: "todos os navegadores", confianca: "alta", origem: "ferramentas do navegador", regras: [] },
  { id: "html-img", lang: "html", tema: "imagens", titulo: "Imagem não aparece no site",
    sintomas: ["imagem nao aparece", "img nao carrega", "foto nao aparece no site", "imagem quebrada"],
    causas: ["Caminho errado no {{src}} (pasta, maiúsculas ou extensão diferente).", "No servidor, nomes são sensíveis a maiúsculas: {{Foto.JPG}} ≠ {{foto.jpg}}."],
    correcoes: ["Confira o caminho relativo a partir do arquivo .html.", "Use nomes sem espaço e em minúsculas."],
    compat: "todos os navegadores", confianca: "alta", origem: "comum em hospedagem", regras: [] },
  { id: "css-rolagem", lang: "css", tema: "layout", titulo: "Site com rolagem pro lado no celular",
    sintomas: ["rolagem lateral", "site saindo da tela", "scroll horizontal", "site mexe pro lado no celular", "sobra espaco na direita"],
    causas: ["Algum elemento mais largo que a tela (imagem grande, {{width}} fixo, {{100vw}}).", "Padding somando na largura (sem {{box-sizing: border-box}})."],
    correcoes: ["{{img { max-width: 100%; }}} e {{* { box-sizing: border-box; }}}", "Troque larguras fixas por {{max-width}}."],
    compat: "todos os navegadores", confianca: "alta", origem: "CSS", regras: [] },

  /* ======================= JAVASCRIPT ======================= */
  { id: "js-botao", lang: "javascript", tema: "DOM", titulo: "Botão não faz nada / \"Cannot read properties of null\"",
    sintomas: ["botao nao faz nada", "cannot read properties of null", "addeventlistener null", "javascript nao funciona", "script nao funciona", "clique nao funciona"],
    causas: ["O {{<script>}} roda **antes** do HTML existir (está no {{<head>}} sem {{defer}}).", "O id no {{getElementById}} está diferente do HTML."],
    correcoes: ["Use {{<script src=\"script.js\" defer></script>}} ou coloque o script no fim do {{<body>}}.", "Abra o Console (F12) pra ver o erro."],
    compat: "navegadores modernos", confianca: "alta", origem: "documentação MDN", regras: [] },
  { id: "js-nan", lang: "javascript", tema: "tipos", titulo: "Resultado NaN ou números juntando (\"2\" + \"2\" = \"22\")",
    sintomas: ["da nan", "resultado nan", "numeros juntando javascript", "soma junta javascript", "value do input soma errado"],
    causas: ["O {{.value}} de um input é **texto**.", "Converteu texto que não é número ({{Number(\"abc\")}} = NaN)."],
    correcoes: ["{{const n = Number(input.value);}} e confira com {{Number.isNaN(n)}}."],
    compat: "ES2015+", confianca: "alta", origem: "documentação MDN", regras: [] },
  { id: "js-not-defined", lang: "javascript", tema: "variáveis", titulo: "\"X is not defined\"",
    sintomas: ["is not defined", "referenceerror", "nao esta definido javascript"],
    causas: ["Variável usada antes de criar, ou criada dentro de outra função/bloco.", "Nome com maiúscula diferente."],
    correcoes: ["Declare com {{let}}/{{const}} antes de usar e no escopo certo."],
    compat: "ES2015+", confianca: "alta", origem: "documentação MDN", regras: [] },
);
